---
- name: Get a list of scheduled template job
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: RUN COMMAND
      register: show_output
      ansible.builtin.raw: |
             curl -k https://controller1.aap-stag.expertsystems.com/api/v2/job_templates/7/schedules/
  #"curl -sk --location 'https://controller1.aap-stag.expertsystems.com/api/v2/job_templates/7/schedules/' --header 'Authorization: Bearer {{AAP_API_token}}'"
      args:
        executable: /bin/bash
    - name: RETURN RESULTS
      debug:
        msg: "{{ show_output }}"
